export const SET_CURRENT_OFFER = `SET_CURRENT_OFFER`;
export const SET_NEAREST_OFFERS = `SET_NEAREST_OFFERS`;
export const SET_REVIEWS = `SET_REVIEWS`;
export const CHANGE_CURRENT_OFFER_STATUS = `CHANGE_CURRENT_OFFER_STATUS`;
