export const SET_CURRENT_OFFER = `CURRENT_OFFER/SET_CURRENT_OFFER`;
export const SET_NEAREST_OFFERS = `CURRENT_OFFER/SET_NEAREST_OFFERS`;
export const SET_REVIEWS = `CURRENT_OFFER/SET_REVIEWS`;
export const CHANGE_CURRENT_OFFER_STATUS = `CURRENT_OFFER/CHANGE_CURRENT_OFFER_STATUS`;
