export default {
  CITIES: `CITIES`,
  OFFERS: `OFFERS`,
  USER: `USER`,
  OFFER_LOCATION: `OFFER_LOCATION`,
  CURRENT_OFFER: `CURRENT_OFFER`,
  COMMENT: `COMMENT`,
  FAVORITES: `FAVORITES`,
  SERVICE_AVAILABLE_STATUS: `SERVICE_AVAILABLE_STATUS`
};
